import xmltodict
import aiohttp
import asyncio
import sys
import hashlib
import pprint

version = sys.argv[1]


def verification_data():
    with open("gradle/verification-metadata.xml") as f:
        data = xmltodict.parse(f.read())
        return data


def artifact(name, hash):
    return {
        "@name": name,
        "sha256": {
            "@origin": "Generated by Gradle",
            "@value": hash,
        },
    }


async def download_and_hash(session, url):
    print(f"=> Downloading {url}")
    async with session.get(url) as response:
        response.raise_for_status()
        return hashlib.sha256(await response.read()).hexdigest()


async def main():

    async with aiohttp.ClientSession() as session:
        print(f"=> Checking if version {version} exists...")
        async with session.get(
            f"https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/{version}/aapt2-{version}.pom"
        ) as response:
            response.raise_for_status()
            pom = hashlib.sha256(await response.read()).hexdigest()
            async with asyncio.TaskGroup() as group:
                windows = group.create_task(
                    download_and_hash(
                        session,
                        f"https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/{version}/aapt2-{version}-windows.jar",
                    )
                )
                osx = group.create_task(
                    download_and_hash(
                        session,
                        f"https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/{version}/aapt2-{version}-osx.jar",
                    )
                )
                linux = group.create_task(
                    download_and_hash(
                        session,
                        f"https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/{version}/aapt2-{version}-linux.jar",
                    )
                )
            data = verification_data()
            data["verification-metadata"]["components"]["component"].append(
                {
                    "@group": "com.android.tools.build",
                    "@name": "aapt2",
                    "@version": version,
                    "artifact": [
                        artifact(f"aapt2-{version}.pom", pom),
                        artifact(f"aapt2-{version}-windows.jar", windows.result()),
                        artifact(f"aapt2-{version}-osx.jar", osx.result()),
                        artifact(f"aapt2-{version}-linux.jar", linux.result()),
                    ],
                }
            )
            with open("gradle/verification-metadata.xml", "w") as f:
                f.write(xmltodict.unparse(data))


asyncio.run(main())
