name: Restore Gradle Cache

runs:
  using: composite
  steps:
  - name: Restore Dependencies Cache
    uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
    with:
      path: |
        ~/.gradle/caches/modules-2/files-2.1/
        ~/.gradle/caches/modules-2/metadata-2.107/
      key: gradle-dependencies-${{ runner.os }}-${{ hashFiles('**/build.gradle*', '**/settings.gradle*', 'gradle/*.versions.toml') }}
      restore-keys: |
        gradle-dependencies-${{ runner.os }}-
  - name: Restore Gradle Kotlin DSL Cache
    uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
    with:
      path: |
        ~/.gradle/caches/*/kotlin-dsl
      key: gradle-kotlin-dsl-${{ runner.os }}-${{ hashFiles('**/build.gradle*', '**/settings.gradle*') }}
      restore-keys: |
        gradle-kotlin-dsl-${{ runner.os }}-
  - name: Restore Gradle Transforms Cache
    uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
    with:
      path: |
        ~/.gradle/caches/*/transforms
      key: gradle-transforms-${{ runner.os }}-${{ hashFiles('**/build.gradle*', '**/settings.gradle*') }}
      restore-keys: |
        gradle-transforms-${{ runner.os }}-
  - name: Restore Gradle Generated JARs Cache
    uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
    with:
      path: |
        ~/.gradle/caches/*/generated-gradle-jars
      key: gradle-generated-gradle-jars-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties') }}
      restore-keys: |
        gradle-generated-gradle-jars-${{ runner.os }}-
  - name: Restore Gradle Wrapper Cache
    uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
    with:
      path: |
        ~/.gradle/wrapper
      key: gradle-wrapper-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties') }}
      restore-keys: |
        gradle-wrapper-${{ runner.os }}-
