naming:
  FunctionNaming:
    ignoreAnnotated: ["Composable", "Test"]
  NoNameShadowing:
    active: false
complexity:
  TooManyFunctions:
    active: false
  LongParameterList:
    active: false
  LongMethod:
    active: false
style:
  UnusedPrivateFunction:
    ignoreAnnotated: ["Preview", "PreviewLightDark", "PreviewDynamicColors"]
  SerialVersionUIDInSerializableClass:
    active: false
  MaxLineLength:
    maxLineLength: 140
  MagicNumber:
    active: false
potential-bugs:
  UnsafeCallOnNullableType:
    active: false # Emits too much noise on :designsystem
Compose:
  CompositionLocalAllowlist:
    active: true
    allowedCompositionLocals:
      - LocalKafkaTheme
      - LocalBackButtonVisibility
  ComposableNaming:
    ignoreAnnotatied: ["Composable"]
