name: Build APKs

on:
  workflow_dispatch:
  merge_group:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC -Dkotlin.daemon.jvm.options=-Xmx4096m
  CI_GRADLE_ARG_PROPERTIES: "--stacktrace"

permissions: {}

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [ debug, release ]
      fail-fast: false
    concurrency:
      group: ${{ github.ref == 'refs/heads/master' && format('build-master-{0}-{1}', matrix.variant, github.sha) || format('build-{0}-{1}', matrix.variant, github.ref)  }}
      cancel-in-progress: true
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          # This might remove tools that are actually needed, if set to "true" but frees about 6 GB
          tool-cache: true
          # All of these default to true, but we should only need the 'android' one (and maybe swap-storage?)
          android: false
          dotnet: true
          haskell: true
          # This takes way too long to run (~2 minutes) and it saves only ~5.5GB
          large-packages: false
          docker-images: true
          swap-storage: false
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # See: https://github.com/actions/checkout/issues/881
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}
          persist-credentials: false
      - name: Configure JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      - name: Restore Cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Export AboutLibraries library definitions
        # Used to run only once
        if: matrix.variant == 'debug'
        run: ./gradlew :app:exportLibraryDefinitions --dependency-verification lenient --continue $CI_GRADLE_ARG_PROPERTIES
      - name: Assemble debug APKs
        id: projectkafka-build
        if: matrix.variant == 'debug'
        run: ./gradlew :app:assembleDebug $CI_GRADLE_ARG_PROPERTIES
      - name: Upload debug APKs
        id: projectkafka-upload
        if: matrix.variant == 'debug'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: projectkafka-debug
          path: |
            app/build/outputs/apk/debug/*-debug.apk
      - name: Create app token for PR comments
        if: matrix.variant == 'debug' && github.event_name == 'pull_request' && steps.projectkafka-upload.conclusion == 'success' && github.repository == github.event.pull_request.head.repo.full_name
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app-token
        with:
          app-id: ${{ vars.HANEKOKORO_BOT_APP_ID }}
          private-key: ${{ secrets.HANEKOKORO_BOT_PRIVATE_KEY }}
      - name: Comment on PR for artifacts link
        if: matrix.variant == 'debug' && github.event_name == 'pull_request' && steps.projectkafka-upload.conclusion == 'success' && github.repository == github.event.pull_request.head.repo.full_name
        uses: NejcZdovc/comment-pr@a423635d183a8259308e80593c96fecf31539c26 # v2.1.0
        with:
          message: |
            **Download Debug Artifacts**: [projectkafka-debug.zip](https://nightly.link/ShadowRZ/ProjectKafka/actions/artifacts/${{ steps.projectkafka-upload.outputs.artifact-id }}.zip)
          # Enables to identify and update existing Ad-hoc release message on new commit in the PR
          identifier: "PROJECTKAFKA_COMMENT_ARTIFACTS"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Compile release sources
        if: ${{ matrix.variant == 'release' }}
        run: ./gradlew :app:assembleRelease $CI_GRADLE_ARG_PROPERTIES
      - name: Save Cache
        uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        if: github.event_name != 'pull_request'
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
