name: '[Codestyle] Comment on Pull Request'

on:
  # SAFETY:
  # Codestyle's build artifacts are SARIF files which are not executable code
  workflow_run: # zizmor: ignore[dangerous-triggers]
    workflows: ['Codestyle']
    types: [completed]

permissions: {}

jobs:
  comment:
    name: Comment on Pull Request
    runs-on: ubuntu-slim
    if: github.event.workflow_run.event == 'pull_request'
    steps:
      - name: Create app token for PR comments
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ vars.HANEKOKORO_BOT_APP_ID }}
          private-key: ${{ secrets.HANEKOKORO_BOT_PRIVATE_KEY }}
          permission-pull-requests: write
      - name: Download all artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          run-id: ${{ github.event.workflow_run.id }}
          merge-multiple: true
      - name: Install Reviewdog
        uses: reviewdog/action-setup@d8edfce3dd5e1ec6978745e801f9c50b5ef80252 # v1.4.0
        with:
          reviewdog_version: nightly
      - name: Run Reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          reviewdog -f=sarif -diff="git diff" -reporter=github-pr-check < build/reports/detekt/all.sarif
          reviewdog -f=sarif -diff="git diff" -reporter=github-pr-check < android-app/build/reports/lint-results-debug.sarif
